### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by magnetophon** [modularev/mooSpace#2]
Thanks for this wonderful reverb, I think it sounds really good!

Could you please add a license, so I can package the dsp for my distro?

**Comment by modularev** [comment]
Thanks for the compliment!

I don‘t really know much about licensing and even less about it in combination with FAUST, but as I‘ve seen some other projects with GNU GPL 3.0 and it seems quite alright, I chose that one, I hope it‘s fine :)

**Comment by magnetophon** [comment]
Thank you!
